---
title: "718 Project"
author: "Umer"
date: "4/5/2022"
output: html_document
---


Section 1.Q1-part(a)
```{r}
myFunc = function(lamda,t) #introducing function for part a which takes value of lamda and time to return output
{
n=2* qpois(0.9999999, t*lamda) #using qpois and multiply it by 2 to have a same count
exp_dist = cumsum(rexp(n, lamda)) #cumulative exponential distribution with n calculated in previous step
#exp_dist
patient_arrival = c() #introducing vector of patient arrival times
for(i in 1:length(exp_dist)) #storing values of the cumulative exponential distribution in the patient arrival time vector
{
  if(exp_dist[i] <= t) #store values only if the patient arrives before 4 pm.
  {
    patient_arrival[i] = exp_dist[i]
  }
  else 
    break
}
#patient_arrival
  
patients_waited = 0         # patients who have had to wait
total_wait = 0     # total waiting time so far
doctor <- c(patient_arrival[1], patient_arrival[1], patient_arrival[1]) # next time at which each doctor is free to see another patient
#doctor
#min(doctor)
for(i in 1:length(patient_arrival)){ #running loop for each patient arriving at the clinic
  w=0 # setting initial wait time for each patient
  patient_arrival[i]=patient_arrival[i]+total_wait #patient arrival plus the time he had to wait because of previous waiting patients
    for(j in 1:length(doctor)){ #running loop for each doctor to see if anyone's free
      if(patient_arrival[i]>=doctor[j]){ #if doctor free.. assign him the time of patient arrival time
        doctor[j]=patient_arrival[i]
      }
    }
  w= max((min(doctor)-patient_arrival[i]),0) # checking how much the patient had to wait for
  total_wait= total_wait+ w #adding patient wait time to total wait time
  if(w>0) 
  {
  patients_waited =patients_waited+1 #if patient has to wait, then add one to the number of patients who have had to wait
  i=i-1 #run loop again for the same patient
  }
  else
  {
    for(j in 1:length(doctor)){ #if patient does not have to wait then assign doctor to that patient
      if(patient_arrival[i]>=doctor[j])
        {
        doctor[j]=patient_arrival[i]+runif(1,5,20)
        break
      }
    }
  }
}
total_patients=length(patient_arrival) #total number of patients is the length of the vector of patients arrival
#patients_waited #patients that had to wait
(if(patients_waited==0){ #if no patients waited then the average wait will be equal to 0
  avg_wait=0
}
else{ # If patients had to wait then calculate the average waiting time
avg_wait=total_wait/patients_waited})
closing_time=max(doctor)

output=c(total_patients, patients_waited , avg_wait, closing_time) #store results in vector
return(output) #return results
}
t <- (16 - 9) * 60 #time value
lamda =1/10 # lamda value
x=myFunc(lamda,t) # calling function and storing in x
#x
{ # output results
cat("number of patients: ",x[1], "  ")
cat("number of patients waited: ",x[2], "  ")
cat("average patient wait: ",x[3], "  ") #average patient wait of the patients who waited
cat("Closing time of clinic: ",9+x[4]/60, "pm  ") #changing time to hours
}

```
answer to part(a) returns different values every time because patients arrival time to the clinic is different every time since running the exponential distribution gives different values.

Section 1,Q1. part (b)
```{r}
{
#introducing empty vectors to store values
total_patients_x=c()
n_waited_x=c()
avg_wait_x=c()
closing_time_x=c()

for(i in 1:1000) #run 1000 times to store values in the vectors
{
  y=myFunc(lamda,t)
  total_patients_x[i]=y[1] #storing values in each vector
  n_waited_x[i]=y[2]
  avg_wait_x[i]=y[3]
  closing_time_x[i]=y[4]
  
}
#median(total_patients_x)
#median(n_waited_x)
#median(avg_wait_x)
#median(closing_time_x)
#output results of part b
cat("median number of patients: ",median(total_patients_x), "  ")
cat("median number of patients waited: ",median(n_waited_x), "  ")
cat("median average patient wait: ",median(avg_wait_x), "  ")
cat("median Closing time of clinic: ",median(9+closing_time_x/60), "pm  ")
}
```
Running part b almost gives similar values each time it is run.

